# Generated by Django 5.0.6 on 2024-06-08 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gid', '0002_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='UserNote',
        ),
        migrations.AlterUniqueTogether(
            name='usernote',
            unique_together={('sight', 'user')},
        ),
    ]
